<template>
   <Scroll class="content">
         <ul>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
           <li>个人信息</li>
         </ul>
   </Scroll>
</template>

<script>
  import Scroll from 'components/common/betterScroll/BetterScroll'
  export default{
    name:'Profile',
    components:{
      Scroll
    }
  }
</script>

<style scoped>
.content{
  height: 300px;
  background-color: red;
  overflow: hidden;
}
</style>
